columns : 
        - time
        - avg_dist
        - avg_loss
        - val_avg_dist
        - val_avg_loss
        - accuracy
        - val_accuracy
log : train_log.txt
refresh : True
multi : True
refresh_time : 2
